# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - dicoding-forumapi-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_USER: developer
      POSTGRES_DB: forumapi
    ports:
      - 5432:5432

  adminer:
    image: adminer:4
    restart: always
    ports:
      - 9000:8080

volumes:
  dicoding-forumapi-volume: