name: "deploy"

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: remote ssh and deploy app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DICODING_SSH_HOST }}
          username: ${{ secrets.DICODING_SSH_USERNAME }}
          password: ${{ secrets.DICODING_SSH_PASSWORD }}
          port: ${{ secrets.DICODING_SSH_PORT }}
          script: |
            cd ~/apps/dicoding-forum-api
            git pull origin master
            sudo docker compose  -f "docker-compose.production.yml" up -d --build dicoding
            sudo docker ps --filter "name=dicoding-forum-api"
